"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const windowScript = fs.readFileSync(path.join(root, "js", "committed-preview-window.js"), "utf8").replace(/\r\n/g, "\n");
const html = fs.readFileSync(path.join(root, "committed-preview.html"), "utf8");
const css = fs.readFileSync(path.join(root, "style.css"), "utf8");
const preview = require(path.join(root, "js", "chordwiki-preview.js"));
const entry = fs.readFileSync(path.join(root, "js", "entries", "committed-preview.js"), "utf8");

assert(windowScript.includes('if (!text.value) { try { text.value = localStorage.getItem(TEXT_KEY) || ""; } catch (_error) {} }\n  // A saved draft'));
assert(windowScript.includes('const keepExistingDraft = new URLSearchParams(window.location.search).get("draft") === "keep";'));
assert(windowScript.includes('if (!keepExistingDraft && !pendingReplace) { try { applyState(JSON.parse(localStorage.getItem(STATE_KEY) || "null")); } catch (_error) {} }'));
const app = fs.readFileSync(path.join(root, "js", "app.js"), "utf8");
assert(app.includes('elements.openRealtimeEditor.href = "committed-preview.html?pending=replace";'));
assert(app.includes("event.preventDefault();"), "cancel must prevent opening the realtime editor");
assert(windowScript.includes('const pendingReplace = new URLSearchParams(window.location.search).get("pending") === "replace";'));
assert(windowScript.includes('id="committed-replace-dialog"') === false && html.includes('id="committed-replace-dialog"'), "replacement choice must be shown inside the realtime editor");
assert(windowScript.includes('replaceDialog.returnValue === "yes"') && windowScript.includes("history.replaceState"), "cancel must leave the old draft and close the one-shot replacement prompt");
assert(windowScript.includes("// numbers, syntax layer, or score preview. Always perform an initial render.\n  render();"));
assert(html.includes('type="module" src="/js/entries/committed-preview.js?v=20260905-013"'));
assert(html.includes('style.css?v=20260905-011'));
assert(css.includes('.committed-window-editor, .committed-window-editor-wrap .editor-highlight { padding: 10px; }'), "realtime editor text and highlight layers must share mobile padding");
assert(css.includes('font-variant-ligatures: none;'), "realtime editor text and highlight layers must use the same glyph shaping");
assert(css.includes('.bold-chords .committed-window-editor-wrap .editor-highlight .syntax-chord { font-weight: 400; text-shadow: 0 0 .35px currentColor; }'), "realtime bold chords must not change the caret measurement width");
assert(entry.includes('await import("../committed-preview-window.js")'));
assert(html.includes('id="committed-layout-toggle"'));
assert(html.includes('id="committed-position-toggle"') && html.includes("コード位置調整モード"), "realtime editor must expose chord position adjustment mode");
assert(!html.includes('id="committed-copy"'), "realtime editor must not add a separate copy button");
assert(html.includes('id="committed-position-help"') && html.includes('id="committed-position-help" class="position-adjust-help" hidden') && html.includes("<kbd>Shift+Space</kbd> 前"), "position adjustment guide must be hidden until the mode starts");
assert(html.includes('id="committed-preview-mode-status"') && html.includes('class="preview-position-status" hidden'), "preview header must expose a mode status hidden outside position adjustment");
assert(html.includes('id="committed-position-symbols"') && html.includes("小節線・ハイフンも移動対象にする"), "position adjustment must offer an optional structural-token target mode");
assert(html.indexOf('id="committed-position-toggle"') > html.indexOf('class="committed-window-editor-pane"'), "position adjustment toggle belongs to the editor pane header");
assert(windowScript.includes('const chordTokenPattern = /\\[\\[([^\\[\\]\\r\\n]*)\\]\\]|\\[([^\\[\\]\\r\\n]*)\\]/g;'), "position adjustment must identify chord tokens");
assert(windowScript.includes('const atStart = ranges.find((range) => position === range.start);') && windowScript.includes('position >= range.start && position < range.end'), "position adjustment clicks at adjacent token boundaries must select the following token");
assert(windowScript.includes('const handlePositionSpace = (event)') && windowScript.includes('event.key === "　"') && windowScript.includes('document.addEventListener("keydown", handlePositionSpace, true)') && windowScript.includes('document.addEventListener("keyup", handlePositionSpace, true)') && windowScript.includes('document.addEventListener("beforeinput", handlePositionBeforeInput, true)') && windowScript.includes('event.data === "　"') && windowScript.includes('event.shiftKey ? -1 : 1'), "half-width and full-width spaces must navigate chord selection without reaching edit or conversion handlers");
assert(windowScript.includes('text.addEventListener("beforeinput"') && windowScript.includes('["historyUndo", "historyRedo"].includes(event.inputType)') && windowScript.includes('event.preventDefault();'), "position adjustment mode must block direct text input while allowing history changes");
assert(windowScript.includes('text.readOnly = true') && windowScript.includes('text.readOnly = false') && windowScript.includes('beforeinput'), "position adjustment mode must block IME and direct text input while restoring editing on exit");
assert(windowScript.includes('text.addEventListener("focus", () => {') && windowScript.includes('if (positionAdjustMode) text.blur();'), "position adjustment mode must immediately remove text focus so the IME cannot handle Space");
assert(windowScript.includes('if ((event.ctrlKey || event.metaKey) && ["a", "c", "z"].includes(event.key.toLowerCase())) return;'), "position adjustment mode must allow select-all, copy and undo shortcuts");
assert(windowScript.includes('const positionUndoStack = []') && windowScript.includes('const undoPositionEdit = ()') && windowScript.includes('document.addEventListener("keydown", handlePositionUndo, true)'), "position adjustment mode must undo scripted movements with Ctrl+Z");
assert(windowScript.includes('const directiveTokenPattern = /\\{[^{}\\r\\n]*\\}/g') && windowScript.includes('const movementRanges = (source)'), "position adjustment must treat brace directives as indivisible movement units");
assert(windowScript.includes('const handlePositionNavigation = (event)') && windowScript.includes('if (["Tab", "Shift", "Control", "Alt", "Meta"].includes(event.key)) return;') && windowScript.includes('event.stopImmediatePropagation();'), "position adjustment mode must block non-navigation keyboard edits");
assert(windowScript.includes('previousCodePointStart') && windowScript.includes('nextCodePointEnd'), "horizontal position adjustment must move by text characters");
assert(windowScript.includes('text.setRangeText(`${range.token}${previousText}`, previousStart, range.end, "select")') && windowScript.includes('text.setRangeText(`${nextText}${range.token}`, range.start, nextEnd, "select")'), "horizontal position adjustment must move the selected token between text characters");
assert(windowScript.includes('const previousToken = positionTokens.find((token) => token.end === range.start)') && windowScript.includes('const nextToken = positionTokens.find((token) => token.start === range.end)'), "horizontal position adjustment must move across one position unit at a time");
assert(windowScript.includes('const tokenSelector = includePositionSymbols') && windowScript.includes('event.target.closest?.(tokenSelector)'), "preview token clicks must select the matching source token");
assert(windowScript.includes('chordRanges(text.value, includePositionSymbols)'), "selection navigation must follow the optional structural-token target mode");
assert(windowScript.includes('positionHelp.hidden = false') && windowScript.includes('positionHelp.hidden = true'), "position adjustment guide must toggle with the mode");
assert(windowScript.includes('previewPane.classList.add("position-adjust-active")') && windowScript.includes('previewModeStatus.hidden = false') && windowScript.includes('previewModeStatus.hidden = true'), "preview header must follow position adjustment mode state");
assert(windowScript.includes('const syncPreviewHeaderHeight = ()') && windowScript.includes('previewTitle.style.height = `${editorTitle.getBoundingClientRect().height}px`'), "preview header must match the editor header height");
assert(css.includes(".editor-highlight .position-adjust-active"), "selected chord must have a position-adjustment highlight");
assert(css.includes(".position-adjust-help[hidden]") && css.includes("display: none !important"), "position adjustment guide must stay hidden outside the mode");
assert(css.includes(".committed-window-preview-pane.position-adjust-active") && css.includes(".preview-position-status[hidden]"), "preview header must expand and hide its mode status outside position adjustment");
assert(css.includes(".position-adjust-option") && css.includes("margin-inline-start: 3em"), "structural-token option must have about three character widths of spacing after the keyboard guide");
assert(css.includes(".committed-window-editor-pane.position-adjust-active") && css.includes(".position-adjust-help kbd"), "position adjustment mode must tint the editor pane and key guide");
assert(!html.includes('id="realtime-draft-dialog"'), "realtime draft choice belongs to the main page, not the editor window");
assert(html.includes('committed-window-layout committed-window-stacked'));
assert(html.includes('href="index.html" aria-label="ChordWiki Bar Formatter トップページへ"'));
assert(html.includes("リアルタイムエディター｜ChordWiki Bar Formatter"));
assert(html.includes('<details class="score-window-settings">'));
assert(windowScript.includes('if (helpPanel?.open && !helpPanel.contains(event.target)) helpPanel.open = false;'), "realtime editor help must close on outside clicks");
assert(windowScript.includes('if (settingsPanel?.open && !settingsPanel.contains(event.target)) settingsPanel.open = false;'), "realtime editor display settings must close on outside clicks");
assert(html.includes('<details class="score-window-help">'));
assert(html.includes('<strong>リアルタイムエディターの使い方</strong>'));
assert(html.includes('右の譜面をクリックすると、対応する左の行を確認できます。'));
assert(html.includes('編集内容はこのブラウザの下書きとして保存されます。元の画面の変換前・変換後は自動更新されません。'));
assert(css.includes('.score-window-help-panel { position: absolute;'));
assert(css.includes(".score-window-settings-panel { position: absolute;"));
assert(html.includes('id="committed-line-height"'));
assert(html.includes('id="committed-transpose"'));
assert(html.includes('id="committed-transpose-down"'));
assert(html.includes('id="committed-transpose-up"'));
assert(
  html.indexOf('id="committed-transpose"') < html.indexOf('id="committed-transpose-down"')
    && html.indexOf('id="committed-transpose-down"') < html.indexOf('id="committed-transpose-up"'),
  "realtime transpose controls must be ordered as no-transpose select, minus, plus"
);
assert(css.includes("grid-template-columns: minmax(88px, 118px) 28px 28px;"));
assert(css.includes(".cw-upper-token-level-2 { position: relative; top: -1.1em; }"));
assert(entry.includes('import "../transposer.js"'));
assert(windowScript.includes('window.ChordWikiTranspose.transposeText(text.value, previewTranspose, "preserve")'));
assert(windowScript.includes("let appliedTranspose = 0;") && windowScript.includes("let transposeCommitted = false;"), "realtime transpose must track text-applied state separately from the selector");
assert(windowScript.includes("const previewTranspose = transposeCommitted ? 0 : Number(transpose.value) || 0;"), "realtime preview must not apply a transpose twice after the editor text is changed");
assert(windowScript.includes("const commitTransposeSelection = () => {") && windowScript.includes("const delta = transposeCommitted ? target - appliedTranspose : target;"), "realtime transpose changes must apply the selected delta to the editor text");
assert(windowScript.includes("text.value = transposed;") && windowScript.includes("publishText();"), "realtime transpose must publish the transposed editor text");
assert(windowScript.includes("transposeApplied: transposeCommitted") && windowScript.includes("appliedTranspose"), "realtime transpose state must persist without changing the existing draft schema");
assert(windowScript.includes('text.value = event.newValue; appliedTranspose = 0; transposeCommitted = false;'), "external realtime text updates must reset the baked transpose tracking");
assert(windowScript.includes('const startedOnBackground = event.target === preview || Boolean(sourceLine);'), "dragging any rendered score line must pan the preview");
assert(windowScript.includes('if (!startedOnBackground || (event.pointerType === "mouse" && event.button !== 0)) return;'));
assert(windowScript.includes('preview.setPointerCapture(event.pointerId);'));
assert(css.includes('.committed-window-preview.is-panning { cursor: grabbing; user-select: none; }'));
assert(css.includes('.committed-window-preview { cursor: grab; touch-action: none; }'), "touch drag must stay available for two-axis preview panning");
assert(html.includes('id="committed-font-size-value"'));
assert(html.includes('id="committed-bold-code" type="checkbox" checked'));
assert(windowScript.includes("const contentLineTop = paddingTop + activeLine * lineHeight;"));
assert(windowScript.includes('text.style.setProperty("--active-line-top", `${contentLineTop - text.scrollTop}px`);'));
assert(windowScript.includes("if (previewRow) previewRow.dataset.sourceLine = String(sourceLineIndex);"));
assert(windowScript.includes('event.target.closest("[data-source-line]")'));
assert(windowScript.includes("const LINE_NUMBER_TRAILING_ROWS = 2"), "realtime editor line numbers must reserve two visual trailing rows");
assert(windowScript.includes('class=\"line-number-spacer\"'), "realtime editor line-number padding must not add text rows");
assert(windowScript.includes('scrollPositionForProgress(element, "top", topProgress)'), "realtime editor must calculate scroll positions from normalized progress");
assert(windowScript.includes('setScrollProgress(preview, scrollSync.checked ? textTopProgress : previewTopProgress'), "realtime editor startup and rerender must restore proportional preview position");
assert(windowScript.includes("scrollPositionWasSuppressed"), "realtime editor linked scroll events must not bounce back and forth");
assert(css.includes("--committed-line-height: 2.75"));
assert(css.includes(".committed-window-editor-wrap .line-numbers span { height: calc(var(--editor-font-size) * var(--committed-line-height)); }"));
assert(css.includes(".committed-window-preview { height: 100%; margin: 0; border: 0; border-radius: 0; font-size: var(--editor-font-size) !important; }"));
assert(css.includes(".committed-window-layout.committed-window-stacked"));
assert(css.includes("--committed-line-height: 1.65"));
assert(windowScript.includes('layoutMode = layoutMode === "side" ? "stacked" : "side"'));
assert(windowScript.includes('let layoutMode = "stacked";'));
assert(windowScript.includes("stackedLineHeight = next; else sideLineHeight = next;"));
assert(windowScript.includes("checkboxDefaultsVersion: 1"));
assert(windowScript.includes("stackedPaneSize, sidePaneSize"));
assert(windowScript.includes("Math.max(6, Math.min(94"));
assert(windowScript.includes("requestAnimationFrame(() => {"));
assert(css.includes(".committed-window-editor.active-line-visible"));
assert(css.includes('.committed-window-preview > [data-source-line].compare-active'));

const rendered = preview.render("[|][C][----]テスト[|]");
assert(rendered.includes('class="line cw-score-line cw-score-line-has-lyrics"'));
assert(rendered.includes('class="cw-code-token"'));
assert(rendered.includes("テスト"));
assert(preview.render("[[C]]上付き").includes("cw-upper-token-level-2"), "realtime preview must share old ChordWiki double-upper rendering");

console.log("PASS: saved realtime drafts always render line numbers, color text, and score preview");
