"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const css = fs.readFileSync(path.join(root, "style.css"), "utf8");
const app = fs.readFileSync(path.join(root, "js", "app.js"), "utf8");

assert(html.includes('<span>小節線[|]にカッコをつけない</span>'));
assert.strictEqual((html.match(/id="added-background"/g) || []).length, 1);
assert(html.includes('<label class="output-diff-setting"><input id="added-background" type="checkbox" checked> <span>差分背景</span></label>'));
assert(!html.includes("自動追加の背景に色付ける"));
const diffBackgroundHandler = app.match(/elements\.addedBackground\.addEventListener\("change", \(\) => \{([\s\S]*?)\n  \}\);/);
assert(diffBackgroundHandler);
assert(diffBackgroundHandler[1].includes("updateEditorHighlight(elements.output)"));
assert(!/scheduleConversion|positionSettingsPanel|syncResultRowAlignment/.test(diffBackgroundHandler[1]));
assert(html.includes('<button id="correction-refresh-line" type="button"'));
assert(html.includes("↻ この行を更新"));
assert(app.includes('correctionRefreshLine: $("#correction-refresh-line")'));
assert(app.includes('elements.correctionRefreshLine.addEventListener("click"'));
assert(app.includes("keepOutputAndRefreshCorrection(lineIndex)"));
assert(css.includes("grid-template-columns: minmax(0, 1fr) minmax(0, 1fr) minmax(0, 1.35fr);"));
assert(html.includes('class="column-resize-edge guide-column-resize-edge"'));
assert(!html.includes('data-panel="guide"'));
assert(css.includes(".correction-input-guide { position: relative; min-width: 0; min-height: 72px; height: auto;"));
assert(css.includes("overflow: visible;"));
assert(css.includes(".guide-column-resize-edge { top: 0; bottom: 0; }"));
assert(!app.includes("guideHeight:"));
assert(!app.includes("layout.guideHeight"));
assert(!html.includes('id="correction-append"'));
assert(!html.includes("＋ 末尾に追加"));
assert(!html.includes("編集時の小節線[|]にカッコをつけない"));
assert(html.includes('id="add-input-brackets" class="sample-header-button bracket-header-button"'));
assert(html.includes('<span>コードに[]を追加</span></button>'));
assert(css.includes(".bracket-header-button { justify-content: center; padding-inline: 7px; white-space: nowrap; }"));
assert(css.includes(".sample-header-button:not(.bracket-header-button) > span:last-child"));
assert(html.includes('id="hyphen-removal-linked" type="checkbox" checked'));
assert(html.includes("初期設定値を使う"));
assert(!html.includes("コード直後のハイフン数と連動"));
assert(app.includes('elements.removalLinked.addEventListener("change"'));
assert(app.includes("elements.removalLinked.checked = false"));
assert(html.includes('id="lyric-hyphen-mode"'));
const showOption = html.indexOf('<option value="show">省略しない</option>');
const targetOption = html.indexOf('<option value="target" selected>指定数だけ省略（カスタム・おすすめ）</option>');
const minimizeOption = html.indexOf('<option value="minimize">できるだけ省略</option>');
const allOption = html.indexOf('<option value="all">すべて省略</option>');
assert(showOption >= 0 && showOption < targetOption && targetOption < minimizeOption && minimizeOption < allOption);
assert.strictEqual((html.match(/class="context-help-button"/g) || []).length, 4);
assert(html.includes("表示方法を選びます。<br>「指定数だけ省略」"));
assert(html.includes("小節位置を調整します。<br>入力例と記号の意味"));
assert(html.includes("譜面に近い形で確認します。<br>移調、音名表記"));
assert(html.includes("初期設定値を使う"));
assert(app.includes("LYRIC_HYPHEN_MODE_STORAGE_KEY"));
assert(app.includes('elements.lyricHyphenMode.addEventListener("change"'));
assert(app.includes("updateLyricHyphenControls"));
assert(!html.includes('id="hide-lyric-hyphens"'));
assert(css.includes("gap: 0 10px; align-items: start;"));
assert(css.includes(".input-card { grid-column: 2; grid-row: 1; align-self: end; }"));
assert(css.includes(".font-panel { grid-column: 1; grid-row: 1; align-self: start; min-width: 0; margin-bottom: 122px; }"));
assert(css.includes(".auxiliary-panel-heading { margin: -9px -12px 9px -10px;"));
assert(html.includes('<div class="output-column-headings" aria-hidden="true"><span>No.</span><span>変換後テキスト</span></div>'));
assert(css.includes(".output-column-headings { grid-column: 1 / -1; grid-row: 1; display: grid; grid-template-columns: subgrid;"));
assert(css.includes(".output-column-headings span:last-child { justify-items: start; padding-left: 1em; border-left: 1px solid var(--line); }"));
assert(html.includes('<div class="left-lower-stack">'));
assert(css.includes(".left-lower-stack { grid-column: 1; grid-row: 3; align-self: start; display: grid; gap: 12px;"));
assert(html.includes('<div class="right-lower-stack">'));
assert(css.includes(".right-lower-stack { grid-column: 2; grid-row: 3; align-self: start; display: grid; gap: 12px;"));
assert(css.includes(".final-card, .committed-card { min-width: 0; margin-top: 0; }"));
assert(css.includes(".status-support-panel { min-width: 0; margin: 0;"));
assert(css.includes(".correction-card { grid-column: 1; grid-row: 2; margin-top: var(--result-controls-offset, 0px); }"));
assert(css.includes(".output-card { grid-column: 2; grid-row: 2; }"));
assert(!css.includes(".committed-card { grid-column: 2; grid-row: 4;"));
assert(!app.includes("--settings-clearance"));

console.log("PASS: header wording and bracket-button text layout");
