"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const css = fs.readFileSync(path.join(root, "style.css"), "utf8");
const app = fs.readFileSync(path.join(root, "js/app.js"), "utf8");
const help = html.match(/<dialog id="help-dialog"[\s\S]*?<\/dialog>/)?.[0] || "";

assert(help.includes('<span class="help-chord">[C]</span>あいうえ<span class="help-chord">[G]</span>お　かき'));
assert(help.includes('なに<span class="help-chord">[Gsus4]</span>ぬねの　は'));
assert(!help.includes("この森"));
assert(!help.includes("満開"));
assert(!help.includes('<span class="help-chord">[C]</span>ChordPro形式の'));
assert(!help.includes("削除ハイフン"));
assert(!help.includes('href="#help-'));
assert(!help.includes("help-jump-nav"));
assert(!help.includes("help-more"));
assert(!help.includes("表示設定を変える"));
assert(!help.includes("最短3ステップ"));
assert(!help.includes("使い方を目的別に見る"));
assert(!help.includes("コード譜を貼ると、小節線と長さ記号が付きます"));
assert(!help.includes("なにができるの？"));
assert(help.includes("このサイトでは何ができますか？"));
assert(help.includes("どんな人・どんな場面に向いていますか？"));
assert(!help.includes("何を入力すればいいですか？"));
assert(help.includes("スマホでも使えますか？"));
assert(help.includes("PCでの利用をおすすめします"));
assert(help.includes('href="https://ja.chordwiki.org/"'));
assert(help.includes('href="https://anipu.web.fc2.com/helper/lyricker.html"'));
assert(help.includes("このツールでできないこと"));
assert(!help.includes("このサイトでできないこと"));
assert(help.includes("コード入力のサポートは行えません。レイアウトに特化したツールです。"));
assert(help.includes("曲に合わせた確認と手動修正が必要です。"));
assert(help.includes("コードを文字間に入力する機能"));
assert(help.includes("[&gt;--&gt;]"));
assert(help.includes("コードのない位置へハイフンを付ける機能"));
assert(help.includes("[|][C][----]あいう[----]えお[|]"));
assert(help.includes("ハイフンはコード直後に付く表記を前提としているため"));
assert.strictEqual((help.match(/class="help-intro-card/g) || []).length, 4);
assert(help.indexOf("はじめに / INTRODUCTION") < help.indexOf("基本的な使い方 / BASIC FLOW"));
assert(help.indexOf("基本的な使い方 / BASIC FLOW") < help.indexOf("変換例 / EXAMPLE"));
assert(help.includes('<h3 id="help-intro-title">はじめに</h3>'));
assert(help.includes('<h3 id="help-flow-title">基本的な使い方</h3>'));
assert(help.includes('<h3 id="help-io-title">変換例</h3>'));
assert(help.includes('<h3 id="help-trouble-title">修正方法</h3>'));
assert(help.includes("修正方法 / HOW TO ADJUST"));
assert(help.includes("コード譜を貼る"));
assert(help.includes("自動変換結果を修正する"));
assert(help.includes("プレビューする"));
assert(help.includes("確定してコピーする"));
assert(!help.includes("どうやって使い始めますか？"));
assert(!help.includes("変換結果はどう直しますか？"));
assert(!help.includes("完成した譜面はどう使いますか？"));
const basicFlow = help.match(/<ol class="help-flow-grid">([\s\S]*?)<\/ol>/)?.[1] || "";
assert(!basicFlow.includes("<p>"));
assert(!basicFlow.includes("help-flow-finish"));
assert.strictEqual((basicFlow.match(/<li>/g) || []).length, 4);
assert(basicFlow.includes("07 確定 / COMMIT"));
assert.strictEqual((help.match(/class="help-io-panel help-io-/g) || []).length, 4);
assert.strictEqual((help.match(/class="help-io-panel-heading"/g) || []).length, 4);
assert(help.includes("<strong>1. コード譜を貼る</strong><small>対象枠：変換前</small>"));
assert(help.includes("<strong>2. 小節線とハイフンが自動追加される</strong><small>対象枠：初期設定、変換後</small>"));
assert(help.includes("<strong>3. 曲に合わせてハイフン数を修正</strong><small>対象枠：行修正</small>"));
assert(help.includes("<strong>4. 修正後を確認</strong><small>対象枠：譜面プレビュー</small>"));
assert.strictEqual((help.match(/class="help-fat-arrow/g) || []).length, 3);
assert.strictEqual((help.match(/class="help-fat-arrow[^>]*">➜/g) || []).length, 3);
assert(help.includes("「4/4拍子の基本設定」で自動変換された例"));
assert.strictEqual((help.match(/class="help-conversion-table(?: |")/g) || []).length, 2);
assert(help.includes("コード直後につく<br>ハイフン数"));
assert(help.includes("44448"));
assert(help.includes("4444"));
assert(help.includes("448"));
assert(help.includes('<code>44<strong class="help-manual-changed-digit">224</strong></code>'));
assert(help.includes("表示省略するハイフン長さ：4,8"));
assert(help.includes('class="help-panel-note help-omit-note"'));
assert(help.includes('class="help-conversion-table help-manual-table"'));
assert.strictEqual((help.match(/class="help-auto-added"/g) || []).length, 24);
assert.strictEqual((help.match(/class="help-example-change"/g) || []).length, 6);
assert.strictEqual((help.match(/class="help-manual-changed-digit"/g) || []).length, 3);
assert(!help.includes("自動変換を土台にして、曲に合わない部分だけ修正します。"));
assert(help.includes("[---]</mark>つて"));
assert(help.includes("[-]</mark>と<mark class=\"help-example-change\">[----]</mark>[|]"));
assert(help.includes('id="help-example-preview" class="help-example-preview chordwiki-preview"'));
assert.strictEqual((help.match(/class="help-task-card"/g) || []).length, 5);
const settingsIndex = help.indexOf("初期設定でハイフン数を変える");
const rowEditIndex = help.indexOf("数字でハイフン数を変える");
const rowModeIndex = help.indexOf("行ごとの採用状態を切り替える");
const recoveryIndex = help.indexOf("行修正のずれを直す");
const finishIndex = help.indexOf("移調し確定する");
assert(settingsIndex >= 0 && settingsIndex < rowEditIndex && rowEditIndex < rowModeIndex && rowModeIndex < recoveryIndex && recoveryIndex < finishIndex);
assert(help.includes("変換前から作った自動変換結果を使います。"));
assert(help.includes("行修正または変換後で直接編集した内容を使います。"));
assert(help.includes("現在の変換後を保持し、行修正による上書きを止めます。"));
assert(help.includes("非対応の表記を検出した行は、内容を守るため自動的に「固定」になる場合があります。"));
assert(help.includes("1行だけずれた場合は「この行を更新」を使います。"));
assert(help.includes("異常時用の「変換後から行修正を復元」で全行を作り直します。"));
assert(help.includes("復元できない行は空欄になります。"));
assert(help.includes("4/4拍子：合計8、コード直後4"));
assert(help.includes("6/8拍子：合計6、コード直後3"));
assert(help.includes("[|][C][----][G][----][|]"));
assert(help.includes("[|][C][---][G][---][|]"));
assert(help.includes("[C][G][Am] ＋ 行修正 224"));
assert(help.includes("[|][C][--][G][--][Am][----][|]"));
assert(help.includes("対象枠：03 初期設定、05 変換後"));
assert(help.includes("対象枠：04 行修正、05 変換後"));
assert(help.includes("対象枠：06 譜面プレビュー、07 確定譜面テキスト"));
assert(!help.includes("対象枠：05 変換後、06 譜面プレビュー、07 確定譜面テキスト"));
assert(help.includes("[D]　[A]　[Bm]"));
assert(help.includes("操作アイコン / ICONS"));
assert(help.includes("アイコン説明"));
assert(!help.includes("見分け方 / REFERENCE"));
assert((help.match(/class="help-chord"/g) || []).length >= 20);
assert(css.includes('--help-example-font: "Courier New", "BIZ UDPGothic", monospace;'));
assert(css.includes("font: 700 .78rem/1.55 var(--help-example-font);"));
assert(css.includes("font: 800 .76rem/1.35 var(--help-example-font);"));
assert(css.includes(".help-example-preview .cw-chord, .help-example-preview .cw-boundary-upper { font-family: inherit; }"));
assert(css.includes(".help-example-preview .cw-score-line { width: max-content; min-width: 100%;"));
assert(css.includes('grid-template-areas: "input forward output output output" ". . . . turn" "preview preview preview back correction";'));
assert(css.includes('grid-template-areas: "input" "forward" "output" "turn" "correction" "back" "preview";'));
assert(css.includes("grid-template-columns: 32% 20px 8% 20px minmax(0, 1fr);"));
assert(css.includes(".help-dialog { width: min(1500px, calc(100% - 12px));"));
assert(css.includes(".help-flow-turn { grid-area: turn; transform: rotate(90deg); }"));
assert(css.includes(".help-flow-back { grid-area: back; transform: rotate(180deg); }"));
assert(css.includes(".help-conversion-table { display: grid;"));
assert(css.includes("grid-template-columns: 9em minmax(0, 1fr);"));
assert(css.includes(".help-conversion-table > strong, .help-conversion-table > code, .help-conversion-table > pre { min-width: 0; margin: 0; padding: 5px 7px; border: 0; }"));
assert(css.includes(".help-conversion-table > strong:first-child { white-space: nowrap; }"));
assert(css.includes(".help-io-output .help-conversion-table > pre { overflow: hidden; white-space: pre; word-break: normal; }"));
assert(css.includes("border-left: 1px solid var(--line);"));
assert(css.includes(".help-conversion-table-wrap { margin-top: 5px; overflow: visible;"));
assert(!css.includes(".help-conversion-table-wrap { margin-top: 5px; overflow-x: auto;"));
assert(css.includes("justify-content: flex-start;"));
assert(css.includes(".help-example-preview.chordwiki-preview"));
assert(app.includes("window.ChordWikiPreview.renderInto(elements.helpExamplePreview, HELP_EXAMPLE_PREVIEW_TEXT)"));
assert(css.includes(".help-flow-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr));"));
assert(css.includes(".help-task-grid { display: grid; grid-template-columns: minmax(0, 1fr);"));
assert(css.includes(".help-task-grid { grid-template-columns: 1fr; }"));
assert(css.includes(".help-state-list { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));"));
assert(css.includes(".help-state-list { grid-template-columns: 1fr; }"));
assert(css.includes(".help-setting-values { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));"));
assert(css.includes(".help-setting-values { grid-template-columns: 1fr; }"));
assert(css.includes(".help-content p, .help-content li, .help-content dt, .help-content dd { color: var(--text); font-weight: 400; }"));
assert(!css.includes(".help-flow-finish"));
assert(css.includes(".help-intro-primary { padding-block: 13px; }"));
assert(css.includes(".help-task-card { display: grid; align-content: start; gap: 6px; min-width: 0; padding: 9px 10px; border: 1px solid var(--line); border-left: 3px solid var(--accent);"));
assert(css.includes(".help-task-card > header { display: grid; grid-template-columns: 26px minmax(0, 1fr);"));
assert(css.includes(".help-task-example-stack > div { display: grid; grid-template-columns: minmax(0, 1fr) auto minmax(0, 1fr);"));
assert(css.includes(".help-manual-table > strong:first-child, .help-manual-table > code"));
assert(css.includes(".help-manual-table > code { font-weight: 600; }"));
assert(css.includes(".help-auto-added {"));
assert(css.includes(".help-example-change {"));
assert(css.includes(".help-manual-changed-digit {"));
assert(css.includes(".help-task-example-stack code { min-width: 0; padding: 4px 6px; border: 0;"));

console.log("PASS: help uses a four-stage wrapped flow, separated rhythm font, bar lines, and practical correction examples");
