"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const css = fs.readFileSync(path.join(root, "style.css"), "utf8");
const app = fs.readFileSync(path.join(root, "js/app.js"), "utf8");
const help = html.match(/<dialog id="help-dialog"[\s\S]*?<\/dialog>/)?.[0] || "";

assert(help.includes('<span class="help-chord">[C]</span>あいうえ<span class="help-chord">[G]</span>お　かき'));
assert(help.includes('なに<span class="help-chord">[Gsus4]</span>ぬねの　は'));
assert(!help.includes("この森"));
assert(!help.includes("満開"));
assert(!help.includes('<span class="help-chord">[C]</span>ChordPro形式の'));
assert(!help.includes("削除ハイフン"));
assert(!help.includes('href="#help-'));
assert(!help.includes("help-jump-nav"));
assert(!help.includes("help-more"));
assert(!help.includes("表示設定を変える"));
assert(!help.includes("最短3ステップ"));
assert(!help.includes("使い方を目的別に見る"));
assert(!help.includes("コード譜を貼ると、小節線と長さ記号が付きます"));
assert(!help.includes("なにができるの？"));
assert(help.includes("演奏しやすい小節表記のコード譜制作を助けるツールです"));
assert(!help.includes("どんな人・どんな場面に向いていますか？"));
assert(!help.includes("何を入力すればいいですか？"));
assert(help.includes("スマホでも使えますか？"));
assert(help.includes("PCでの利用を推奨します"));
assert(help.includes('href="https://ja.chordwiki.org/"'));
assert(help.includes('href="https://anipu.web.fc2.com/helper/lyricker.html"'));
assert(help.includes("5. このツールが苦手なこと"));
assert(help.includes("コードを入力する機能："));
assert(help.includes("ChordWiki 用コード譜エディター"));
assert(!help.includes("曲どおりに完全自動で完成させる機能："));
assert(help.includes("小節線やリズム記号を追加して整えるツール"));
assert(help.includes("音源を聞きながら手動で修正してください。"));
assert(help.includes("コードを歌詞の文字間へ入力する機能"));
assert(help.includes("[&gt;--&gt;]"));
assert(help.includes("特殊・複雑なリズム表記："));
assert(!help.includes("コードのない位置へのハイフンの自動割り当て"));
assert(help.includes("小節線とハイフンを自動追加"));
assert(help.includes("コードの長さを簡単修正"));
assert(help.includes("| C ----　--　Am -- |"));
assert(help.includes("[|][C][----]あい[--]う[Am][--]えお[|]"));
assert(help.includes("リズム記号を簡単追加"));
assert(help.includes("譜面を移調"));
assert(!help.includes("完成したコード譜をコピー"));
assert(help.includes("[|][C][----]あいう[Am][----]えお[|]"));
assert(!help.includes('[C] [----]'));
assert.strictEqual((help.match(/class="help-capability-row(?: |")/g) || []).length, 5);
assert(help.includes("アクセント</em>"));
assert(help.includes("白玉</em>"));
assert(help.includes("シンコペーション(-)</em>"));
assert(help.includes("シンコペーション(=)</em>"));
assert(help.includes("リアルタイムプレビュー</strong><span class=\"help-capability-comment\""));
assert(help.includes("「リアルタイムエディター」も使えます。"));
assert(!help.includes('class="help-capability-output"'));
assert(help.includes("ハイフン食い</em>"));
assert(help.includes("[|][C][---=]あいう[Am][=]え[----]お[|]"));
assert(help.includes("<b>/</b><em>アウフタクト</em>"));
assert(help.includes("[C][--]あ[|][Am][----]いう[G][----]えお[|]"));
assert(help.indexOf("<b>*s</b><em>イコール食い</em>") < help.indexOf("<b>/</b><em>アウフタクト</em>"));
assert.strictEqual((help.match(/class="help-intro-card/g) || []).length, 4);
assert(help.includes("入力したコード譜は送信されますか？"));
assert(help.includes("<small>FAQ</small>"));
assert(help.includes("挙動がおかしくなりました。"));
assert(help.indexOf('id="help-trouble-title"') < help.indexOf('id="help-faq-title"'));
assert(help.indexOf("1. このツールについて") < help.indexOf("2. 基本的な使い方"));
assert(help.indexOf("2. 基本的な使い方") < help.indexOf("3. 実際の変換例"));
assert(help.includes('<h3 id="help-intro-title">1. このツールについて</h3>'));
assert(help.includes('<h3 id="help-flow-title">2. 基本的な使い方</h3>'));
assert(help.includes('<h3 id="help-io-title">3. 実際の変換例</h3>'));
assert(help.includes('<small>HOW TO ADJUST</small><strong id="help-trouble-title">4. 詳しい修正方法</strong>'));
assert(help.includes("HOW TO ADJUST"));
assert(help.includes("基本操作に慣れたら見てみる"));
assert(help.includes('<small>LIMITATIONS</small><strong>5. このツールが苦手なこと</strong>'));
assert(help.includes("気になったときに見てみる"));
assert.strictEqual((help.match(/<details[^>]*class="[^"]*help-collapsible[^"]*"/g) || []).length, 2);
assert(!help.includes('class="help-trouble help-collapsible" open'));
assert(!help.includes('class="help-limitations help-collapsible" open'));
assert(help.includes("コード譜を貼る"));
assert(help.includes("曲に合わせて<br>調整"));
assert(help.includes("譜面を確認して<br>完成！"));
assert(help.includes("拍子と設定値を<br>確認する"));
assert(help.includes("譜面を確認して<br>完成！"));
assert(!help.includes("どうやって使い始めますか？"));
assert(!help.includes("変換結果はどう直しますか？"));
assert(!help.includes("完成した譜面はどう使いますか？"));
const basicFlow = help.match(/<ol class="help-flow-grid">([\s\S]*?)<\/ol>/)?.[1] || "";
assert.strictEqual((basicFlow.match(/<p>/g) || []).length, 4);
assert(!basicFlow.includes("help-flow-finish"));
assert.strictEqual((basicFlow.match(/<li>/g) || []).length, 4);
assert(basicFlow.includes("05. 譜面プレビュー／リアルタイムエディター"));
assert(!basicFlow.includes("<span>5</span>"));
assert(basicFlow.includes("本サイトへ投稿します。"));
assert.strictEqual((help.match(/class="help-io-panel help-io-/g) || []).length, 4);
assert.strictEqual((help.match(/class="help-io-panel-heading"/g) || []).length, 4);
assert(help.includes("<strong>1. コード譜を貼る</strong><small>対象枠：01. 変換前</small>"));
assert(help.includes("<strong>2. 小節線とハイフンが自動追加される</strong><small>対象枠：02. 初期設定、04. 変換後</small>"));
assert(help.includes("<strong>3. 曲に合わせてハイフン数を修正</strong><small>対象枠：03. 行修正</small>"));
assert(help.includes("<strong>4. 譜面プレビューで確認する</strong><small>対象枠：05. 譜面プレビュー</small>"));
assert.strictEqual((help.match(/class="help-fat-arrow/g) || []).length, 3);
assert.strictEqual((help.match(/class="help-fat-arrow[^>]*">➜/g) || []).length, 3);
assert(help.includes("「4/4拍子の基本設定」で自動変換された例"));
assert.strictEqual((help.match(/class="help-conversion-table(?: |")/g) || []).length, 2);
assert(help.includes("コード直後につく<br>ハイフン数"));
assert(help.includes("44448"));
assert(help.includes("4444"));
assert(help.includes("448"));
assert(help.includes('<code>44<strong class="help-manual-changed-digit">224</strong></code>'));
assert(help.includes("見やすくするために省略するハイフン長さ：4,8"));
assert(help.includes('class="help-table-heading-note"'));
assert(!help.includes('class="help-panel-note help-omit-note"'));
assert(help.includes('class="help-conversion-table help-manual-table"'));
assert.strictEqual((help.match(/class="help-auto-added"/g) || []).length, 24);
assert.strictEqual((help.match(/class="help-example-change"/g) || []).length, 6);
assert.strictEqual((help.match(/class="help-manual-changed-digit"/g) || []).length, 3);
assert(!help.includes("自動変換を土台にして、曲に合わない部分だけ修正します。"));
assert(help.includes("[---]</mark>つて"));
assert(help.includes("[-]</mark>と<mark class=\"help-example-change\">[----]</mark>[|]"));
assert(help.includes('id="help-example-preview" class="help-example-preview chordwiki-preview"'));
assert.strictEqual((help.match(/class="help-task-card"/g) || []).length, 6);
const settingsIndex = help.indexOf("初期設定でハイフン数を変える");
const rowEditIndex = help.indexOf("数字でハイフン数を変える");
const syncopationIndex = help.indexOf("シンコペーションを設定する");
const rowModeIndex = help.indexOf("自動／修正／固定を切り替える");
const recoveryIndex = help.indexOf("行修正のずれを直す");
const finishIndex = help.indexOf("移調して確定する");
assert(settingsIndex >= 0 && settingsIndex < rowEditIndex && rowEditIndex < syncopationIndex && syncopationIndex < rowModeIndex && rowModeIndex < recoveryIndex && recoveryIndex < finishIndex);
assert(help.includes("自動変換の結果を使います。"));
assert(help.includes("「03. 行修正」の内容を使います。"));
assert(help.includes("直接編集したときなどに切り替わり、自動で書き換えません。"));
assert(help.includes("状態は内容を読み取って自動で切り替わります。"));
assert(help.includes("1行だけ変"));
assert(help.includes("たくさんの行が変"));
assert(help.includes("「この行を更新」"));
assert(help.includes("「変換後から行修正を復元」"));
assert(!help.includes("読み取れない行だけ、行修正が空欄になります。"));
assert(help.includes("4/4拍子：合計8、コード直後4"));
assert(help.includes("6/8拍子：合計6、コード直後3"));
assert(help.includes("[|][C][----]あいう[Am][----]えお[|]"));
assert(help.includes("6/8拍子：合計6、コード直後3"));
assert(help.includes("<b>224</b>"));
assert(help.includes("[|][C][--][G][--][Am][----][|]"));
assert(help.includes("対象枠：02. 初期設定、04. 変換後"));
assert(help.includes("対象枠：03. 行修正、04. 変換後"));
assert(help.includes("対象枠：05. 譜面プレビュー、確定譜面テキスト"));
assert(!help.includes("対象枠：05 変換後、06 譜面プレビュー、07 確定譜面テキスト"));
assert(help.includes("D　　 A　　 Bm"));
assert(!help.includes("操作アイコン / ICONS"));
assert(!help.includes("アイコン説明"));
assert(!help.includes("見分け方 / REFERENCE"));
assert((help.match(/class="help-chord"/g) || []).length >= 20);
assert(css.includes('--help-example-font: "BIZ UDPGothic", "Meiryo", sans-serif;'));
assert(css.includes("font: 700 .78rem/1.55 var(--help-example-font);"));
assert(css.includes("font: 800 .76rem/1.35 var(--help-example-font);"));
assert(css.includes(".help-example-preview .cw-chord, .help-example-preview .cw-boundary-upper { font-family: inherit; }"));
assert(css.includes(".help-example-preview .cw-score-line { width: max-content; min-width: 100%;"));
assert(css.includes(".help-example-preview .cw-score-line > .cw-segment:first-child:not(.cw-segment-has-upper) .cw-body { left: 0; }"));
assert(css.includes('grid-template-areas: "input forward output output output" ". . . . turn" "preview preview preview back correction";'));
assert(css.includes('grid-template-areas: "input" "forward" "output" "turn" "correction" "back" "preview";'));
assert(css.includes("grid-template-columns: 32% 20px 8% 20px minmax(0, 1fr);"));
assert(css.includes(".help-dialog { width: min(1500px, calc(100% - 12px));"));
assert(css.includes(".help-flow-turn { grid-area: turn; transform: rotate(90deg); }"));
assert(css.includes(".help-flow-back { grid-area: back; transform: rotate(180deg); }"));
assert(css.includes(".help-conversion-table { display: grid;"));
assert(css.includes("grid-template-columns: 9em minmax(0, 1fr);"));
assert(css.includes(".help-conversion-table > strong, .help-conversion-table > code, .help-conversion-table > pre { min-width: 0; margin: 0; padding: 5px 7px; border: 0; }"));
assert(css.includes(".help-conversion-table > strong:first-child { white-space: nowrap; }"));
assert(css.includes(".help-io-output .help-conversion-table > pre { overflow: hidden; white-space: pre; word-break: normal; }"));
assert(css.includes("border-left: 1px solid var(--line);"));
assert(css.includes(".help-conversion-table-wrap { margin-top: 5px; overflow: visible;"));
assert(!css.includes(".help-conversion-table-wrap { margin-top: 5px; overflow-x: auto;"));
assert(css.includes("justify-content: flex-start;"));
assert(css.includes(".help-example-preview.chordwiki-preview"));
assert(app.includes("window.ChordWikiPreview.renderInto(elements.helpExamplePreview, HELP_EXAMPLE_PREVIEW_TEXT)"));
assert(css.includes(".help-flow-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr));"));
assert(css.includes('background: linear-gradient(135deg, color-mix(in srgb, var(--panel) 84%, var(--step-color))'));
assert(css.includes('.help-flow-grid li:not(:last-child)::after { content: "➜";'));
assert(css.includes(".help-flow { max-width: 1400px; }"));
assert(css.includes(".help-flow-grid li > div { display: contents; }"));
assert(css.includes(".help-flow-grid li p { grid-column: 1 / -1;"));
assert(css.includes("grid-template-rows: auto minmax(2.56em, auto) auto;"));
assert(css.includes(".help-flow-grid li > span { grid-row: 1 / 3;"));
assert(css.includes(".help-state-list .help-state-auto"));
assert(css.includes(".help-state-list .help-state-edit"));
assert(css.includes(".help-state-list .help-state-lock"));
assert(css.includes(".help-recovery-guide { display: grid;"));
assert(css.includes(".help-output-token + .help-output-token { margin-left: 0; }"));
assert(css.includes('font-family: "BIZ UDPGothic", "Meiryo", sans-serif;'));
assert(css.includes("grid-template-columns: 7.5em max-content max-content max-content;"));
assert(css.includes("justify-content: start;"));
assert(css.includes("clip-path: polygon("));
assert(help.includes("<b>自動</b>"));
assert(help.includes("<b>62</b>"));
assert(help.includes("<b>^</b>"));
assert(help.includes("<b>@</b>"));
assert(help.includes("<b>s</b>"));
assert(help.includes("<b>*s</b>"));
assert(help.includes("<b>+2</b>"));
assert(help.includes('class="help-mini-score"'));
assert.strictEqual((help.match(/class="help-rendered-pair"/g) || []).length, 14);
assert.strictEqual((help.match(/class="help-chordpro-pair"/g) || []).length, 2);
assert.strictEqual((help.match(/class="help-operation help-operation-only"/g) || []).length, 12);
assert(help.includes("[|][C][====]あいう[Am][====]えお[|]"));
assert(help.includes("| C ○ ----　Am ---- |"));
assert(help.includes("[|][C][---]あいう[Am][-]え[----]お[|]"));
assert(help.includes("[|][C][---=]あいう[Am][=]え[----]お[|]"));
assert(css.includes(".help-rendered-pair, .help-chordpro-pair"));
assert(css.includes(".help-preview-arrow { grid-column: 3; grid-row: 1; display: block; width: 100%; min-height: 3.4em;"));
assert(css.includes("grid-template-columns: 7.5em minmax(0, 1.45fr) 3.2em minmax(250px, .75fr);"));
assert(help.includes("変換前の原文："));
assert(help.includes('class="help-example-source-preview"'));
assert(help.includes('aria-label="変換前の譜面プレビュー"'));
assert(help.includes("この入力が、下のように変わります。"));
assert(!help.includes("<small>例</small>"));
assert(css.includes("grid-template-columns: 205px minmax(0, 1fr);"));
assert(css.includes(".help-capability-row:has(> .help-rhythm-examples) { grid-template-columns: 205px minmax(0, 1fr);"));
assert(css.includes(".help-rhythm-examples .help-operation { align-self: stretch; }"));
assert(css.includes(".help-rhythm-examples .help-operation b { max-width: 100%; }"));
assert(css.includes(".help-operation { grid-column: 1; grid-row: 1; display: grid; grid-template-columns: minmax(0, 1fr); align-self: center; gap: 2px; width: 100%; min-width: 0; }"));
assert(css.includes("width: 100%; min-width: 0; height: 40px; min-height: 40px; font-size: .82rem;"));
assert(!css.includes(".help-capability-row:not(:nth-child(4)) .help-rendered-pair > .help-mini-score:last-child > span { padding-left: 1.5em; }"));
assert(css.includes(".help-preview-second-lyric { display: inline; }"));
assert(!css.includes(".help-preview-second-lyric { display: inline; margin-left: 2em; }"));
assert(css.includes(".help-mini-score .cw-score-line { width: max-content; min-width: 100%; margin: 1em 0 .1em;"));
assert(css.includes(".help-mini-score { display: grid;") && css.includes("color: #15200e; background: #fbfcf7;"), "ミニ譜面はライト・ダーク両テーマで高コントラストを保つ");
assert(app.includes("function renderHelpMiniScores()") && app.includes('document.querySelectorAll(".help-capability-example")'), "ヘルプのミニ譜面もChordProレンダラーで表示する");
assert(css.includes(".help-state-list .help-state-edit { --state-color: var(--correction-line); }"));
assert(css.includes(".help-state-list .help-state-lock { --state-color: #d5912c; }"));
assert(css.includes(".help-task-grid { display: grid; grid-template-columns: minmax(0, 1fr);"));
assert(css.includes(".help-task-grid { grid-template-columns: 1fr; }"));
assert(css.includes(".help-state-list { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));"));
assert(css.includes(".help-state-list { grid-template-columns: 1fr; }"));
assert(css.includes(".help-setting-values { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));"));
assert(css.includes(".help-setting-values { grid-template-columns: 1fr; }"));
assert(css.includes(".help-content p, .help-content li, .help-content dt, .help-content dd { color: var(--text); font-weight: 400; }"));
assert(!css.includes(".help-flow-finish"));
assert(css.includes(".help-intro-primary { padding-block: 13px; }"));
assert(css.includes('.help-limitations code { font-variant-ligatures: none; font-feature-settings: "liga" 0; }'));
assert(css.includes(".help-task-card { display: grid; align-content: start; gap: 6px; min-width: 0; padding: 9px 10px; border: 1px solid var(--line); border-left: 3px solid var(--accent);"));
assert(css.includes(".help-task-card > header { display: grid; grid-template-columns: 26px minmax(0, 1fr);"));
assert(css.includes(".help-task-example-stack > div { display: grid; grid-template-columns: minmax(0, 1fr) auto minmax(0, 1fr);"));
assert(css.includes(".help-manual-table > strong:first-child, .help-manual-table > code"));
assert(css.includes(".help-manual-table > code { font-weight: 600; }"));
assert(css.includes(".help-auto-added {"));
assert(css.includes(".help-example-change {"));
assert(css.includes(".help-manual-changed-digit {"));
assert(css.includes(".help-task-example-stack code { min-width: 0; padding: 4px 6px; border: 0;"));

console.log("PASS: help uses a five-step basic flow, preserved conversion tables, and collapsed reference sections");
