"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const check = require(path.join(root, "js", "measure-check.js"));
const html = fs.readFileSync(path.join(root, "committed-preview.html"), "utf8");
const entry = fs.readFileSync(path.join(root, "js", "entries", "committed-preview.js"), "utf8");
const css = fs.readFileSync(path.join(root, "style-measure-check.css"), "utf8");

const matching = check.validate("[|][C][>---][G][≧===][|][Am][---][F][---][|]");
assert.strictEqual(matching.ok, true, "accent and half-note symbols must contribute to the beat total");
assert.deepStrictEqual(matching.rhythmMeasures.map((measure) => measure.beats), [6, 6]);
assert.strictEqual(check.rhythmWidth("＞＝＝"), 4, "full-width ＞＝＝ must represent a two-beat triplet");
const triplet = check.validate("[|][C][＞＝＝][|][G][＞＝＝][|]");
assert.strictEqual(triplet.ok, true, "full-width two-beat triplets must match across measures");
assert.deepStrictEqual(triplet.rhythmMeasures.map((measure) => measure.beats), [2, 2]);

const mismatch = check.validate("[|][C][----][G][----][|][Am][----][F][----][|][Dm][----][|]");
assert.strictEqual(mismatch.ok, false);
assert.strictEqual(mismatch.beatIssues.length, 1);
assert.strictEqual(mismatch.beatIssues[0].measure, 3);
assert.match(mismatch.beatIssues[0].message, /拍の長さが違います/);
assert.strictEqual(check.formatMeasureSource(mismatch.beatIssues[0]), "|[Dm][----]|", "beat explanations must show the measure bars");
const beatAdjustment = check.proposeBeatAdjustment(mismatch.beatIssues[0]);
assert.strictEqual(beatAdjustment.token, "----", "beat adjustment should use a readable rhythm token");
assert.strictEqual(beatAdjustment.after, "|[Dm][----][----]|", "beat adjustment should show a concrete corrected measure");
assert.strictEqual(beatAdjustment.replacement, "[Dm][----][----]", "applying a beat adjustment must preserve the surrounding bars");
const halfBeatAdjustment = check.proposeBeatAdjustment(check.validate("[|][C][--------][|][Dm][=][|]").beatIssues[0]);
assert.strictEqual(halfBeatAdjustment.token, "-------=", "odd half-beat gaps must use a final half-beat symbol");
assert.strictEqual(check.validate(halfBeatAdjustment.after).rhythmMeasures[0].beats, 8, "odd half-beat adjustments must reach the target beat count");
assert.strictEqual(check.validate(beatAdjustment.after).rhythmMeasures[0].beats, mismatch.beatIssues[0].expectedBeats, "the concrete beat adjustment must reach the target beat count");
const analyzed = check.analyzeMeasureRhythm({ measureSource: "[F][---=]編集[G][=]お[----]疲れ" });
assert.deepStrictEqual(analyzed.parts.map((part) => [part.token, part.beats]), [["[---=]", 3.5], ["[=]", 0.5], ["[----]", 4]]);
assert.strictEqual(analyzed.totalBeats, 8, "rhythm analysis must sum only the rhythm tokens in the measure");
const continuedMeasure = check.validate("[|][F][---]入力[G][-]で[----]きま[|][C][○][----]す\n[F][----]細かい部分は[|]");
assert.strictEqual(continuedMeasure.ok, true, "an unclosed measure must continue across a line break until the next bar");
assert.deepStrictEqual(continuedMeasure.rhythmMeasures.map((measure) => measure.beats), [8, 8]);
assert.strictEqual(continuedMeasure.rhythmMeasures[1].line, 1, "a continued measure keeps the line where it started");
assert.strictEqual(continuedMeasure.rhythmMeasures[1].measure, 2, "a continued measure keeps its starting line measure number");
assert.strictEqual(check.beatText(0.5), "0.5拍分");
assert.ok(check.validate("[|][C][][|]").syntaxIssues.some((issue) => /空の角括弧/.test(issue.message)));

const noBeat = check.validate("[|][C][○][|][Am][----][F][----][|]");
assert.strictEqual(noBeat.ok, true, "a measure with no beat markers is allowed and excluded from comparison");
assert.strictEqual(noBeat.noBeatMeasureCount, 1);

const syntax = check.validate("[|][C][---x][|][G][----]");
assert.strictEqual(syntax.ok, false);
assert.ok(syntax.syntaxIssues.some((issue) => /リズム記号/.test(issue.message)));
assert.ok(check.validate("[|][C][----").syntaxIssues.some((issue) => /閉じ括弧/.test(issue.message)));

const recommendation = check.proposeSixteenthAccentNotation("[|][C][>====][|]\n[|][G][＞＝＝][|]");
assert.strictEqual(recommendation.changes, 1);
assert.strictEqual(recommendation.after, "[|][C][≧====][|]\n[|][G][＞＝＝][|]");
assert.match(recommendation.summary, /変更前：\[\|\]\[C\]\[>====\]/);
assert.strictEqual(check.proposeSixteenthAccentNotation("[|][G][＞＝＝][|]"), null, "full-width triplets must not be rewritten as sixteenth accents");
assert.strictEqual(check.rhythmWidth(">="), 2, "a > followed by = is one plus one fine-width unit");
assert.strictEqual(check.rhythmWidth("---="), 7, "three hyphens plus one half-beat symbol must equal 3.5 beats");

const fixSource = "[|][C][][|]\n[|][G]----][|]";
const fixResult = check.validate(fixSource);
const emptyFix = fixResult.syntaxIssues.find((issue) => issue.code === "empty-bracket");
const strayFix = fixResult.syntaxIssues.find((issue) => issue.code === "stray-closing-bracket");
assert(emptyFix && strayFix, "safe syntax fixes must expose source positions");
assert.strictEqual(check.applyFixes(fixSource, [check.issueFix(emptyFix), check.issueFix(strayFix)]), "[|][C][|]\n[|][G]----[|]");

assert(html.includes('id="committed-measure-check"'));
assert(html.includes('id="committed-measure-check-panel"'));
assert(html.includes('id="committed-measure-check-expand-all"'));
assert(html.includes('id="committed-measure-check-apply-all"'));
assert(html.includes("安全な対策をすべて適用"), "bulk apply must be clearly limited to safe automatic fixes");
assert(css.includes('.committed-measure-check-button::before { content: "▼";') && css.includes('.committed-measure-check-button[aria-expanded="true"]::before { content: "▲"; }'), "the check button must show its open/closed state");
assert(entry.includes('import "../measure-check.js?v=20260905-007"'));
assert(entry.includes('import "../committed-measure-check-panel.js?v=20260905-007"'));
const panel = fs.readFileSync(path.join(root, "js", "committed-measure-check-panel.js"), "utf8");
assert(panel.includes("checker?.validate(output.value)"));
assert(panel.includes('button.addEventListener("click"'));
assert(panel.includes("event.preventDefault();") && panel.includes("event.stopPropagation();"), "the check button must keep its click behavior isolated");
assert(panel.includes("render(panel.hidden);"), "the check button must toggle the result panel");
assert(panel.includes('applyAllButton?.addEventListener("click"'));
assert(panel.includes('expandAllButton?.addEventListener("click"'));
assert(panel.includes('applyRecommendationButton?.addEventListener("click"'));
assert(panel.includes('rejectRecommendationButton?.addEventListener("click"'));
assert(!panel.includes("原因と対策"));
assert(panel.includes("measure-check-explanation-label"));
assert(panel.includes("小節線「|」の内側"));
assert(panel.includes("自動修正案"));
assert(panel.includes("解析："));
assert(panel.includes("formatRhythmAnalysis"));
assert(panel.includes("記号「${part.token}」は${beatText(part.beats)}"));
assert(panel.includes("合計${beatText(analysis.totalBeats)}"));
assert(panel.includes("修正を適用"));
assert(panel.includes("行へ移動"));
assert(panel.includes("focusIssue(issue)"));
assert(panel.includes("applyBeatSuggestion"));
assert(panel.includes("getBeatSuggestion"));
assert(panel.includes("expectedBeatText"));
assert(panel.includes("小節チェックの結果表示に失敗しました。"));
assert(panel.includes('comparison.classList.add("single")'));
assert(panel.includes("proposeBeatAdjustment"));
assert(panel.includes("調整例"));
assert(panel.includes("formatMeasureSource"));
assert(panel.includes("行へ移動"));
assert(panel.includes("この対策を実行"));
assert(panel.includes("appendVisualExplanation"));
assert(css.includes(".measure-check-code-comparison"));
assert(css.includes(".measure-check-code-line mark"));
assert(css.includes("font-size: .8rem; line-height: 1.5"), "measure-check explanations must be readable at the default size");
assert(css.includes(".measure-check-detail-body { padding: 2px 0 5px; color: var(--text); font-size: .78rem; }"), "measure-check details must be larger than the compact helper labels");
assert(css.includes(".committed-measure-check-panel { margin: 0 5px 6px; padding: 5px 8px; overflow: auto; max-height: min(42vh, 360px); }"), "the realtime check panel should stay compact");
assert(html.includes('id="committed-measure-check-recommendation"'));
assert(html.includes("OK：修正を反映"));
assert(html.includes("NG：変更しない"));
assert(css.includes(".measure-check-panel.has-errors"));
assert(css.includes(".measure-check-recommendation"));

console.log("PASS: realtime editor checks measure syntax, beat consistency, accents, and no-beat measures");
