"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const css = fs.readFileSync(path.join(root, "style.css"), "utf8");
const app = fs.readFileSync(path.join(root, "js", "app.js"), "utf8");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");

assert(css.includes("@media (max-width: 699px)"), "narrow screens must use the linked-editor layout");
assert(css.includes(".score-window-toolbar { grid-template-columns: minmax(0, 1fr);"), "the realtime editor toolbar must place controls below the title on mobile");
assert(css.includes(".score-window-heading h1 { overflow: hidden; font-size: clamp(.82rem, 4vw, .96rem); text-overflow: ellipsis; white-space: nowrap; }"), "the realtime editor title must stay horizontal on mobile");
assert(css.includes(".settings-panel { position: relative; z-index: 30; grid-column: 1; grid-row: 1; width: 100%; height: 72px;"), "settings must stay compact and may overlay row editing when expanded");
assert(css.includes(".correction-card { grid-column: 1; grid-row: 3; transform: none; }"), "row editing must follow source and settings without desktop alignment movement on mobile");
assert(html.includes("class=\"correction-symbol-toolbar\""), "mobile row editing needs a one-row symbol toolbar");
assert(html.includes("class=\"output-symbol-toolbar\""), "mobile result editing needs a one-row input toolbar");
assert(html.includes("data-correction-move=\"ArrowLeft\""), "row editing toolbar must include cursor movement");
assert(html.includes("data-correction-backspace"), "row editing toolbar must include backspace");
assert(html.includes("data-output-insert=\"○\""), "result toolbar must include the circle symbol");
assert(html.includes("data-output-insert=\" \""), "result toolbar must include a half-width space button");
assert(html.includes("data-output-backspace"), "result toolbar must include backspace");
assert(css.includes(".correction-symbol-toolbar { grid-column: 1; grid-row: 4; }"), "symbol toolbar must sit above the result on mobile");
assert(css.includes(".output-card { grid-column: 1; grid-row: 5; margin-top: 0; }"), "result editing must sit below the symbol toolbar on mobile");
assert(css.includes(".output-symbol-toolbar { grid-column: 1; grid-row: 6;"), "result toolbar must sit below the result on mobile");
assert(css.includes(".right-lower-stack { grid-column: 1; grid-row: 7; margin-top: 0; }"), "preview and committed score must directly follow the result toolbar on mobile");
assert(css.includes(".left-lower-stack { grid-column: 1; grid-row: 8; margin-top: 0; }"), "support and related tools must follow the committed score on mobile");
assert(app.includes("moveOutputCursor"), "result toolbar must move the output caret");
assert(app.includes("[data-correction-move]"), "row editing toolbar must move the correction cursor");
assert(css.includes("--result-editor-height: clamp(108px, 19vh, 148px)"), "mobile linked editors must remain compact enough to view together");
assert(!html.includes("id=\"correction-support-toggle\""), "row editing must not show a redundant support collapse button");
assert(html.includes('id="output-settings-toggle" class="mobile-heading-toggle" type="button" aria-expanded="true"'), "result settings must be toggled from its heading");
assert(app.includes("setMobileOutputSettingsOpen(true);"), "result settings must start open on narrow screens");
assert(app.includes("setMobilePreviewSettingsOpen(true);"), "preview settings must start open on narrow screens");
assert(html.includes("id=\"output-settings-mobile\""), "result settings must use a compact collapsible container");
assert(html.includes("id=\"preview-settings-toggle\""), "preview settings must be toggled from its heading");
assert(html.includes("id=\"preview-settings-mobile\""), "preview settings must have a collapsible container");
assert(html.includes("class=\"committed-actions\""), "committed score controls must use their own row");
assert(!app.includes("setMobileCorrectionSupportOpen"), "row-edit actions must remain available without mobile collapse state");
assert(css.includes(".input-card > .frame-resize-corner, .correction-card > .frame-resize-corner, .output-card > .frame-resize-corner, .final-card > .frame-resize-corner { display: block;"), "mobile source, row-edit, result and preview frames must keep an easy-to-grab resize corner");
assert(!css.includes(".settings-panel > .frame-resize-corner, .correction-card > .frame-resize-corner"), "mobile settings must not expose a resize corner");
assert(css.includes("@media (max-width: 380px)"), "very narrow phones must stack result-setting fields cleanly");
assert(css.includes("#input-text, #output-text, #final-output-text, #committed-output-text, #final-score-preview { overflow-x: scroll; scrollbar-gutter: stable; }"), "all long-text panes must keep their native horizontal scrollbar visible");
assert(css.includes("::-webkit-scrollbar:horizontal"), "native horizontal scrollbars must be comfortably thick");
assert(app.includes("closeCorrectionGuideOnNarrowLayout"), "the row-edit symbol guide must close on narrow screens");
assert(app.includes("applyMobileSectionCollapse"), "mobile settings and support must apply their initial open state");
assert(app.includes('window.matchMedia("(max-width: 699px)").matches'), "desktop 03/04 editor alignment must not move the stacked mobile layout");
assert(app.includes("setMobilePreviewSettingsOpen"), "preview settings must follow the mobile collapse state");
assert(app.includes("const allowColumnResize = !window.matchMedia(\"(max-width: 699px)\").matches;"), "mobile resize corners must not change the single-column layout width");
assert(app.includes("function keepMobileLinkedLineInView(lineIndex)"), "active mobile rows must have a linked viewport follower");
assert(app.includes("mobileLinkedScrollPaused = true"), "manual scrolling must temporarily pause automatic following");
assert(app.includes("if (lineChanged) mobileLinkedScrollPaused = false"), "moving to a new line must resume following");

console.log("PASS: narrow screens stack linked editors and preserve manual scrolling");
