"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "musicxml-converter.html"), "utf8");
const css = fs.readFileSync(path.join(root, "musicxml-converter.css"), "utf8");
const page = fs.readFileSync(path.join(root, "js", "musicxml-converter-page.js"), "utf8");
const theme = fs.readFileSync(path.join(root, "js", "musicxml-theme.js"), "utf8");
const converter = fs.readFileSync(path.join(root, "js", "musicxml-converter.js"), "utf8");

assert.match(html, /id="source-toggle"[^>]*aria-expanded="true"/, "01 must be open by default and have a disclosure control");
assert.match(html, /id="report-toggle"[^>]*aria-expanded="true"/, "02 must be open by default and have a disclosure control");
assert(!html.includes('class="card-toggle-mark" aria-hidden="true">⌃</span>'), "disclosure controls must use triangle symbols");
assert.match(html, /class="card-toggle-mark" aria-hidden="true">▲<\/span>/, "disclosure controls must show an up triangle when open");
assert.match(html, /id="source-details"/, "01 details must be independently collapsible");
assert.match(html, /id="report-details-panel"/, "02 details must be independently collapsible");
assert.match(html, /id="warnings"[^>]*hidden/, "warnings must be hidden until there is something to show");
assert.match(html, /<a class="converter-back-link" href="index\.html">ChordWiki Bar Formatterへ戻る<\/a>/, "the converter must offer a compact return path to the Formatter");
assert(!html.includes("対象パート"), "the report must not expose an implementation-specific target part");
assert(!html.includes('id="part-name"'), "the report must not render a target part field");
assert(!html.includes('class="report-details"'), "all standard report metrics must share the compact row");
assert.match(css, /grid-template-columns:minmax\(0,1fr\) minmax\(0,1fr\)/, "01/02 must give the report column a useful desktop width");
assert.match(css, /\.converter-grid\{[^}]*align-items:stretch/, "01 and 02 must have the same row height on desktop");
assert.match(html, /id="report-tools-toggle"/, "the report heading must expose a compact adjustment toggle");
assert.match(html, /[>▶]BPM設定/, "the adjustment toggle must explain which settings it opens");
assert.match(html, /<h2[^>]*>[^<]*<\/h2>[\s\S]*id="report-tools-toggle"/, "the adjustment toggle must sit beside the report heading");
assert.match(html, /class="report-tools(?: |\")/, "the adjustment toggle and panel must share one toolbar");
assert.match(html, /class="report-tools report-tools--header"/, "the adjustment button and panel must share a fixed heading anchor");
const reportHeadingStart = html.indexOf('<header class="editor-heading ui-card__header">', html.indexOf('report-card'));
const reportHeadingEnd = html.indexOf('</header>', reportHeadingStart);
const reportHeadingMarkup = html.slice(reportHeadingStart, reportHeadingEnd);
assert(reportHeadingMarkup.indexOf('id="report-tools-toggle"') < reportHeadingMarkup.indexOf('id="result-status"'), "the adjustment button must come before the conversion status");
assert(!html.includes('id="report-tempo-current"'), "tempo explanation text must be removed from the compact panel");
assert(!html.includes('id="report-key-current"'), "key explanation text must be removed from the compact panel");
assert.match(html, /id="report-tools-panel"/, "the report must contain the hidden adjustment panel");
assert.match(css, /\.report-heading-actions\{/, "the report heading must expose a right-side action group");
assert.match(css, /\.report-tools--header\{[^}]*position:relative/, "the adjustment anchor must keep the button position stable");
assert.match(css, /\.report-tools--header \.report-tools-panel:not\(\[hidden\]\)\{[^}]*position:absolute/, "the report adjustment panel must open without shifting the button");
assert.match(css, /\.report-tools--header \.report-tools-panel:not\(\[hidden\]\)\{[^}]*top:0/, "the compact panel must open over the report heading");
assert.match(css, /\.report-tools--header \.report-tools-panel:not\(\[hidden\]\)\{[^}]*width:min\(260px/, "the adjustment panel must stay compact");
assert.match(css, /\.report-tools-panel\[hidden\]\{display:none\}/, "the closed report adjustment panel must not consume space");
assert.match(css, /\.report-tools\.is-open\{[^}]*border/, "the open adjustment toolbar must have a unified frame");
assert.match(page, /data-tempo-factor/, "the report adjustment panel must expose tempo multiplier controls");
assert(!html.includes('data-tempo-factor="0.25"'), "the report adjustment panel must keep only the three requested tempo multipliers");
assert(!html.includes('data-tempo-factor="0.125"'), "the report adjustment panel must not expose unsupported tempo multipliers");
assert.match(page, /applyTempoFactor\(/, "tempo multiplier controls must affect the generated output");
assert.match(page, /textContent = `\$\{open \? '◀' : '▶'\}BPM設定`/, "the adjustment toggle must keep its purpose visible when opened or closed");
assert.match(page, /open \? '◀' : '▶'/, "the adjustment toggle must point back when the inline panel is open");
assert(!html.includes("平行調切替"), "the report adjustment panel must not expose the removed parallel-key control");
assert(!page.includes("reportKeyToggle"), "parallel-key state must be removed from the page controller");
assert.match(page, /scaleMusicXmlTempoMarkers\(text, tempoFactor\)/, "tempo multiplier controls must reflow output bars");
assert.match(css, /\.metrics\{display:grid;grid-template-columns:repeat\(5,minmax\(0,1fr\)\)/, "the five standard report metrics must fit on one row");
assert.match(css, /\.drop-zone\{min-height:42px;flex-direction:row/, "01 must keep file selection compact while remaining open");
assert.match(css, /\.drop-zone>span:not\(\.upload-icon\)\{white-space:nowrap;font-size:\.72rem/, "the drag-and-drop guidance must remain on one line");
assert.match(css, /\.converter-card\.is-collapsed \.card-details\{display:none/, "collapsed cards must retain only their headings");
assert.match(page, /function bindCardDisclosure\(/, "the page must bind the two disclosure controls");
assert.match(page, /applyMusicXmlTimeChangeMarkers\(latest\.chordWiki, latest\.measures\)/, "restored MusicXML results must retain visible meter-change markers");
assert.match(page, /inputCard\.classList\.toggle\('is-replacing', replacing\)/, "dragging a replacement file must enter the replacement state");
assert.match(page, /dropZone\.classList\.toggle\('hidden', !replacing\)/, "dragging a replacement file must reveal the waiting drop zone");
assert.match(page, /\$\('drop-zone'\)\.classList\.add\('hidden'\)/, "leaving the replacement state must restore the loaded-file summary");
assert.match(css, /\.converter-input-card\.is-replacing \.file-summary\{display:none/, "the loaded-file summary must be hidden while a replacement is dragged over it");
assert.match(css, /\.converter-input-card\.is-replacing \.drop-zone\.hidden\{display:flex!important/, "the waiting drop zone must be visible while a replacement is dragged over it");
assert.match(page, /warningPanel\.hidden = messages\.length === 0/, "a warning-free conversion must not show an empty notice");
assert.match(page, /warningPanel\.classList\.toggle\('is-error'/, "fatal XML errors must use a distinct warning state");
assert.match(page, /元のXMLを手動で修正してから/, "fatal XML errors must explain that the source needs manual repair");
assert.match(page, /warning-reload-button/, "warnings must offer a direct path to choose a corrected XML file");
assert.match(page, /fileInput\.click\(\)/, "the warning action must open the existing XML file picker");
assert.match(page, /setWarnings\(\[\]\)/, "idle and loading states must keep warnings hidden");
assert(!page.includes("$('part-name')"), "page state must not update a removed target part field");
assert.match(html, /id="abbreviation-controls"/, "the result header must expose abbreviation controls");
assert.match(html, /id="musicxml-transpose"/, "the result header must expose a transpose selector");
assert.match(html, /id="musicxml-transpose-down"/, "the result header must expose a transpose down button");
assert.match(html, /id="musicxml-transpose-up"/, "the result header must expose a transpose up button");
assert(!html.includes('<script src="js/transposer.js"></script>'), "MusicXML output must not depend on an unbundled transposer script path");
assert.match(page, /import ['"]\.\/transposer\.js['"]/, "MusicXML page module must bundle the shared transposer");
assert.match(html, />略記切替<\/span>/, "abbreviation controls must have a clear label");
assert.match(html, /data-abbreviation="major"/, "major abbreviation control must be present");
assert.match(html, /data-abbreviation="major"[^>]*>M7<\/button>/, "major control must use the standard M7 form");
assert.match(html, /data-abbreviation="augmented"/, "augmented abbreviation control must be present");
assert.match(html, /data-abbreviation="diminished"/, "diminished abbreviation control must be present");
assert.match(html, /data-abbreviation="halfDiminished"/, "half-diminished abbreviation control must be present");
const abbreviationStart = html.indexOf('id="abbreviation-controls"');
const abbreviationEnd = html.indexOf('</div>', abbreviationStart);
const abbreviationMarkup = html.slice(abbreviationStart, abbreviationEnd);
assert(abbreviationMarkup.indexOf('data-abbreviation="major"') < abbreviationMarkup.indexOf('data-abbreviation="diminished"'), "major must come before diminished");
assert(abbreviationMarkup.indexOf('data-abbreviation="diminished"') < abbreviationMarkup.indexOf('data-abbreviation="augmented"'), "diminished must come before augmented");
assert(abbreviationMarkup.indexOf('data-abbreviation="augmented"') < abbreviationMarkup.indexOf('data-abbreviation="halfDiminished"'), "augmented must come before half-diminished");
assert.match(page, /applyChordWikiAbbreviations/, "page output must render the selected abbreviation form");
assert.match(page, /musicxmlConverter\.abbreviations\.v2/, "abbreviation defaults must migrate to the new standard");
assert.match(page, /MUSICXML_TRANSPOSE_STORAGE_KEY/, "transpose selection must have browser storage");
assert.match(page, /localStorage\.setItem\(MUSICXML_TRANSPOSE_STORAGE_KEY/, "transpose selection must be persisted");
assert.match(page, /preserveTranspose/, "restored results must distinguish saved transpose from new XML conversion");
assert.match(page, /ChordWikiTranspose\.transposeText/, "page output must apply the selected transpose");
assert.match(page, /navigator\.clipboard\.writeText\(outputPreview\.value\)/, "copy must use the displayed abbreviation form");
assert.match(html, /id="output-empty-state"[^>]*>MusicXMLファイルを選択すると、ここに変換結果が表示されます。<\/div>/, "empty output state must explain what to do before a file is selected");
assert.match(html, /id="output-preview"[^>]*aria-labelledby="output-title"[^>]*readonly/, "empty output textarea must be named and read-only");
assert.match(html, /class="editor-tools result-utility-tools"/, "color toggle and copy must share one result utility group");
const resultUtilityStart = html.indexOf('class="editor-tools result-utility-tools"');
const resultUtilityEnd = html.indexOf('</div>', resultUtilityStart);
const resultUtilityMarkup = html.slice(resultUtilityStart, resultUtilityEnd);
assert(resultUtilityMarkup.includes('id="text-coloring"') && resultUtilityMarkup.includes('id="copy-button"'), "color toggle and copy must remain together in the result utility group");
assert.match(html, /<script src="js\/musicxml-theme\.js"><\/script>/, "MusicXML page must apply the saved theme before its styles render");
assert.match(page, /import \{ confirmManualOutput \} from ['"]\.\/musicxml-output-state\.js['"]/, "output regeneration must use the shared edit-safety guard");
assert.match(page, /generatedOutput/, "the page must retain the latest generated output as the manual-edit baseline");
assert.match(page, /window\.confirm\(text\)/, "destructive output changes must ask for confirmation");
assert.match(page, /setEmptyOutputState\(/, "the page must use a dedicated empty output state");
assert.match(page, /outputPreview\.addEventListener\('input', renderOutput\)/, "manual ChordPro edits must keep the colored overlay synchronized");
assert.match(converter, /export function applyChordWikiAbbreviations\(/, "converter must expose abbreviation transformation");
assert.match(converter, /major:\s*'M'/, "major abbreviation defaults must use M");
assert.match(converter, /halfDiminished:\s*'m7-5'/, "half-diminished abbreviation defaults must be defined");
assert.match(converter, /qualityAndBass === 'M'|qualityAndBass\.startsWith\('M'\)/, "major M notation must preserve its extension when switching back");
assert.match(converter, /qualityAndBass === 'o'|qualityAndBass\.startsWith\('o'\)/, "diminished o notation must remain switchable");
assert(!converter.includes("if (qualityAndBass === EMPTY) qualityAndBass = major;"), "plain major chords must not gain a maj suffix");
assert.match(css, /\.abbreviation-controls button\{[^}]*border-radius:4px/, "abbreviation choices must look like compact buttons");
assert.match(css, /\.report-card \.status\{[^}]*border-radius:4px/, "conversion status must use a rectangular frame");
assert.match(css, /\.report-card \.status\{[^}]*white-space:pre-line/, "conversion status must preserve its intentional line break");
assert.match(css, /\.warnings\.is-error\{[^}]*background:/, "fatal XML errors must have a yellow warning background");
assert.match(css, /\.warnings-list\{[^}]*max-height:min\(/, "long warning lists must stay within a compact report area");
assert.match(css, /\.warnings-list\{[^}]*overflow:auto/, "long warning lists must be scrollable");
assert.match(css, /\.warnings-actions/, "warnings must expose a correction action area");
assert.match(page, /: '変換\\n完了'/, "completed status must break after 変換");
assert.match(css, /\.output-card\{[^}]*resize:vertical/, "output card must resize vertically only");
assert(!css.match(/\.output-card\{[^}]*resize:both/), "output card must not resize horizontally");
assert.match(css, /\.output-card\{[^}]*min-height:0/, "output card must not have a fixed minimum height");
assert.match(css, /\.output-card\{[^}]*max-height:none/, "output card must not have a fixed maximum height");
assert.match(css, /\.output-card\{[^}]*align-self:start/, "output card must not stretch to the grid row height");
assert.match(css, /\.output-empty-state\{/, "empty output state must have its own compact presentation");
assert.match(css, /\.output-card\.is-placeholder \.output-text-layer\{display:none/, "empty output state must hide the large editor area");
assert.match(css, /\.output-preview:focus-visible\{/, "output focus must remain visible for keyboard users");
assert.match(css, /\.report-tools--header \.report-tools-toggle\{[^}]*z-index:11/, "the fixed report toggle must remain clickable above the open panel");
assert.match(css, /\.result-utility-tools\{/, "result utility controls must align as one compact group");
assert.match(css, /var\(--warning-text\)/, "warning text must use a theme-aware color");
assert.match(css, /var\(--warning-bg\)/, "warning backgrounds must use a theme-aware color");
assert.match(theme, /chordWikiBarFormatter\.theme\.v1/, "MusicXML theme bootstrap must read the shared theme preference");
assert.match(theme, /dataset\.theme/, "MusicXML theme bootstrap must apply the theme to the document root");
assert(!css.match(/\.output-card\.is-placeholder\{[^}]*min-height/), "placeholder output card must not reintroduce a fixed minimum height");
assert.match(css, /\.musicxml-transpose-control\{order:2\}/, "mobile output controls must put transpose before abbreviations");
assert.match(css, /\.abbreviation-controls\{order:3;flex-basis:100%/, "mobile output controls must put abbreviations after transpose");
assert.match(css, /\.output-card \.editor-tools\{order:4;/, "mobile output controls must put copy and color tools after abbreviations");
assert.match(css, /\.converter-input-card\{order:1\}/, "mobile cards must start with the MusicXML input card");
assert.match(css, /\.report-card\{order:2\}/, "mobile cards must put the report after the input card");
assert.match(css, /\.output-card\{[^}]*order:3/, "mobile cards must put the output after the report");
assert.match(css, /\.converter-output-followup\{order:4\}/, "mobile guidance and related links must come after the output card");

const reportStart = html.indexOf('<article class="converter-card report-card"');
const reportEnd = html.indexOf('</article>', reportStart);
const reportMarkup = html.slice(reportStart, reportEnd);
assert(reportMarkup.indexOf('id="time-signature"') < reportMarkup.indexOf('id="bpm"'), "report must put time signature before BPM");
assert(reportMarkup.indexOf('id="bpm"') < reportMarkup.indexOf('id="measure-count"'), "report must put measure count after BPM");
assert(!reportMarkup.includes('id="key-signature"'), "report must not render the key metric");
assert(reportMarkup.indexOf('id="measure-count"') < reportMarkup.indexOf('id="harmony-count"'), "report must put harmony count after measure count");
