"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "musicxml-converter.html"), "utf8");
const css = fs.readFileSync(path.join(root, "musicxml-converter.css"), "utf8");
const page = fs.readFileSync(path.join(root, "js", "musicxml-converter-page.js"), "utf8");
const converter = fs.readFileSync(path.join(root, "js", "musicxml-converter.js"), "utf8");

assert.match(html, /id="source-toggle"[^>]*aria-expanded="true"/, "01 must be open by default and have a disclosure control");
assert.match(html, /id="report-toggle"[^>]*aria-expanded="true"/, "02 must be open by default and have a disclosure control");
assert(!html.includes('class="card-toggle-mark" aria-hidden="true">⌃</span>'), "disclosure controls must use triangle symbols");
assert.match(html, /class="card-toggle-mark" aria-hidden="true">▲<\/span>/, "disclosure controls must show an up triangle when open");
assert.match(html, /id="source-details"/, "01 details must be independently collapsible");
assert.match(html, /id="report-details-panel"/, "02 details must be independently collapsible");
assert.match(html, /id="warnings"[^>]*hidden/, "warnings must be hidden until there is something to show");
assert.match(html, /<a class="converter-back-link" href="index\.html">ChordWiki Bar Formatterへ戻る<\/a>/, "the converter must offer a compact return path to the Formatter");
assert(!html.includes("対象パート"), "the report must not expose an implementation-specific target part");
assert(!html.includes('id="part-name"'), "the report must not render a target part field");
assert(!html.includes('class="report-details"'), "all standard report metrics must share the compact row");
assert.match(css, /grid-template-columns:minmax\(0,1\.35fr\) minmax\(250px,\.65fr\)/, "01/02 must use a compact asymmetric desktop layout");
assert.match(css, /\.converter-grid\{[^}]*align-items:stretch/, "01 and 02 must have the same row height on desktop");
assert.match(css, /\.metrics\{display:grid;grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/, "the four standard report metrics must fit on one row");
assert.match(css, /\.drop-zone\{min-height:42px;flex-direction:row/, "01 must keep file selection compact while remaining open");
assert.match(css, /\.drop-zone>span:not\(\.upload-icon\)\{white-space:nowrap;font-size:\.72rem/, "the drag-and-drop guidance must remain on one line");
assert.match(css, /\.converter-card\.is-collapsed \.card-details\{display:none/, "collapsed cards must retain only their headings");
assert.match(page, /function bindCardDisclosure\(/, "the page must bind the two disclosure controls");
assert.match(page, /warningPanel\.hidden = messages\.length === 0/, "a warning-free conversion must not show an empty notice");
assert.match(page, /warningPanel\.classList\.toggle\('is-error'/, "fatal XML errors must use a distinct warning state");
assert.match(page, /元のXMLを手動で修正してから/, "fatal XML errors must explain that the source needs manual repair");
assert.match(page, /setWarnings\(\[\]\)/, "idle and loading states must keep warnings hidden");
assert(!page.includes("$('part-name')"), "page state must not update a removed target part field");
assert.match(html, /id="abbreviation-controls"/, "the result header must expose abbreviation controls");
assert.match(html, /id="musicxml-transpose"/, "the result header must expose a transpose selector");
assert.match(html, /id="musicxml-transpose-down"/, "the result header must expose a transpose down button");
assert.match(html, /id="musicxml-transpose-up"/, "the result header must expose a transpose up button");
assert(!html.includes('<script src="js/transposer.js"></script>'), "MusicXML output must not depend on an unbundled transposer script path");
assert.match(page, /import ['"]\.\/transposer\.js['"]/, "MusicXML page module must bundle the shared transposer");
assert.match(html, />略記切替<\/span>/, "abbreviation controls must have a clear label");
assert.match(html, /data-abbreviation="major"/, "major abbreviation control must be present");
assert.match(html, /data-abbreviation="major"[^>]*>M7<\/button>/, "major control must use the standard M7 form");
assert.match(html, /data-abbreviation="augmented"/, "augmented abbreviation control must be present");
assert.match(html, /data-abbreviation="diminished"/, "diminished abbreviation control must be present");
assert.match(html, /data-abbreviation="halfDiminished"/, "half-diminished abbreviation control must be present");
const abbreviationStart = html.indexOf('id="abbreviation-controls"');
const abbreviationEnd = html.indexOf('</div>', abbreviationStart);
const abbreviationMarkup = html.slice(abbreviationStart, abbreviationEnd);
assert(abbreviationMarkup.indexOf('data-abbreviation="major"') < abbreviationMarkup.indexOf('data-abbreviation="diminished"'), "major must come before diminished");
assert(abbreviationMarkup.indexOf('data-abbreviation="diminished"') < abbreviationMarkup.indexOf('data-abbreviation="augmented"'), "diminished must come before augmented");
assert(abbreviationMarkup.indexOf('data-abbreviation="augmented"') < abbreviationMarkup.indexOf('data-abbreviation="halfDiminished"'), "augmented must come before half-diminished");
assert.match(page, /applyChordWikiAbbreviations/, "page output must render the selected abbreviation form");
assert.match(page, /musicxmlConverter\.abbreviations\.v2/, "abbreviation defaults must migrate to the new standard");
assert.match(page, /MUSICXML_TRANSPOSE_STORAGE_KEY/, "transpose selection must have browser storage");
assert.match(page, /localStorage\.setItem\(MUSICXML_TRANSPOSE_STORAGE_KEY/, "transpose selection must be persisted");
assert.match(page, /preserveTranspose/, "restored results must distinguish saved transpose from new XML conversion");
assert.match(page, /ChordWikiTranspose\.transposeText/, "page output must apply the selected transpose");
assert.match(page, /navigator\.clipboard\.writeText\(outputPreview\.value\)/, "copy must use the displayed abbreviation form");
assert.match(converter, /export function applyChordWikiAbbreviations\(/, "converter must expose abbreviation transformation");
assert.match(converter, /major:\s*'M'/, "major abbreviation defaults must use M");
assert.match(converter, /halfDiminished:\s*'m7-5'/, "half-diminished abbreviation defaults must be defined");
assert.match(converter, /qualityAndBass === 'M'|qualityAndBass\.startsWith\('M'\)/, "major M notation must preserve its extension when switching back");
assert.match(converter, /qualityAndBass === 'o'|qualityAndBass\.startsWith\('o'\)/, "diminished o notation must remain switchable");
assert(!converter.includes("if (qualityAndBass === EMPTY) qualityAndBass = major;"), "plain major chords must not gain a maj suffix");
assert.match(css, /\.abbreviation-controls button\{[^}]*border-radius:4px/, "abbreviation choices must look like compact buttons");
assert.match(css, /\.report-card \.status\{[^}]*border-radius:4px/, "conversion status must use a rectangular frame");
assert.match(css, /\.report-card \.status\{[^}]*white-space:pre-line/, "conversion status must preserve its intentional line break");
assert.match(css, /\.warnings\.is-error\{[^}]*background:/, "fatal XML errors must have a yellow warning background");
assert.match(page, /: '変換\\n完了'/, "completed status must break after 変換");
assert.match(css, /\.output-card\{[^}]*resize:vertical/, "output card must resize vertically only");
assert(!css.match(/\.output-card\{[^}]*resize:both/), "output card must not resize horizontally");
assert.match(css, /\.output-card\{[^}]*min-height:0/, "output card must not have a fixed minimum height");
assert.match(css, /\.output-card\{[^}]*max-height:none/, "output card must not have a fixed maximum height");
assert.match(css, /\.output-card\{[^}]*align-self:start/, "output card must not stretch to the grid row height");
assert(!css.match(/\.output-card\.is-placeholder\{[^}]*min-height/), "placeholder output card must not reintroduce a fixed minimum height");

const reportStart = html.indexOf('<article class="converter-card report-card">');
const reportEnd = html.indexOf('</article>', reportStart);
const reportMarkup = html.slice(reportStart, reportEnd);
assert(reportMarkup.indexOf('id="time-signature"') < reportMarkup.indexOf('id="bpm"'), "report must put time signature before BPM");
assert(reportMarkup.indexOf('id="bpm"') < reportMarkup.indexOf('id="measure-count"'), "report must put measure count after BPM");
assert(reportMarkup.indexOf('id="measure-count"') < reportMarkup.indexOf('id="harmony-count"'), "report must put harmony count after measure count");
