"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const css = fs.readFileSync(path.join(root, "style.css"), "utf8");
const readme = fs.readFileSync(path.join(root, "README.md"), "utf8");
const license = fs.readFileSync(path.join(root, "LICENSE"), "utf8");

assert(html.includes("https://mapida222.booth.pm/items/8642112"));
assert(html.includes("https://mapida2.fanbox.cc/plans"));
assert(html.includes("https://docs.google.com/forms/d/e/1FAIpQLScYAHIEEOtuk8MoQR_1sNN7SVgCFFRtKCeUkm23sqTIGqg-cQ/viewform"));
assert(html.includes("報告・要望"));
assert(html.includes("https://github.com/mapida222/ChordWiki-Bar-Formatter-Web"));
assert(html.includes("https://www.chordlistener.com/editor/"));
assert(html.includes("https://mapida222.github.io/ChordWiki-Bar-Formatter-Web/"));
assert(html.includes("https://anipu.web.fc2.com/helper/lyricker.html"));
assert(html.includes("worris様"));
assert(html.includes("fluno様"));
assert(html.includes('src="logo/logo_ChordWikiBarFormatter1.png"'));
assert.strictEqual((html.match(/src="logo\/logo_ChordWikiBarFormatter1\.png"/g) || []).length, 2);
assert(html.includes('src="logo/logo_GitHub_Lockup_White.png"'));
assert(html.includes("<h3>サイト情報・関連ツール <span>/ SITE &amp; TOOLS</span></h3>"));
assert(html.includes("<span>（worris様）</span>"));
assert(html.includes("<span>（ぐらふぃーむ様）</span>"));
assert(html.includes("<span>（fluno様）</span>"));
assert(!html.includes("ChordWiki公式サイト</a>　非公式ツールです。"));
assert(html.includes("https://ja.chordwiki.org/"));
assert(html.includes("制作："));
assert(html.includes("© 2026 mapida"));
assert(!html.includes("ChordWiki運営者のmapidaが、個人で制作した"));
assert(!html.includes("運営元とは関係ありません"));
assert(!html.includes("fanbox.cc/manage/plans"));
assert(!html.includes("1Rm8bOSxlRNkhEa3l8eVPsWUr_OXVBuDFqnoHwc1BMZg/edit"));
assert(html.includes("報告・要望（Googleフォーム）"));
assert(!html.includes('class="community-feedback-icon"'));
assert.strictEqual((html.match(/>↗</g) || []).length, 0);
assert.strictEqual((html.match(/>開く</g) || []).length, 0);
assert(!css.includes('content: "開く"'));
assert(html.includes('aria-label="このツールのリンク"'));
assert(html.includes('<details class="support-menu">'));
assert(html.includes("<span>開発を応援する</span>"));
assert(html.includes("<strong>単発応援/BOOTH</strong>"));
assert(html.includes("<strong>継続応援/FANBOX</strong>"));
assert(!html.includes("単発・100円から"));
assert(!html.includes("定期的な応援はこちら"));
assert.strictEqual((html.match(/class="support-choice /g) || []).length, 2);
assert(css.includes(".community-actions { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr));"));
assert(css.includes(".community-panel { width: 100%; min-width: 0;"));
assert(css.includes(".community-panel .community-panel-heading { margin: -9px -10px 8px;"));
assert(css.includes("height: 34px; min-height: 34px;"));
assert(!css.includes(".community-feedback-icon"));
assert(css.includes(".community-tools { display: grid; gap: 1px;"));
assert(css.includes(".community-tools a { display: grid; grid-template-columns: minmax(0, 1fr); grid-template-areas: \"title\" \"author\";"));
assert(html.includes('<small class="community-section-label">サイト情報</small>'));
assert(html.indexOf('class="community-actions"') < html.indexOf('class="site-credit"'));
assert(css.includes(".community-self-links { display: flex; align-items: center; justify-content: flex-start; gap: 6px; min-width: 0; }"));
assert(!css.includes(".community-actions { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); align-items: start; gap: 6px; margin-top: 7px; padding-top:"));
assert(css.includes(".support-menu[open] .support-menu-caret"));
assert(!css.includes("transform: translateY(-2px)"));
assert(html.indexOf('class="status-support-panel"') < html.indexOf('class="community-panel"'));
assert(html.indexOf('class="community-panel"') < html.indexOf('class="editor-card input-card"'));
assert(readme.includes("[MIT License](LICENSE)"));
assert(license.replace(/\r\n/g, "\n").startsWith("MIT License\n"));
assert(license.includes("Copyright (c) 2026 mapida"));

console.log("PASS: public feedback, support and credit links");
